name: konsul_dok
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icon_poliklinik/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Black.ttf
        - asset: assets/fonts/outfit/Outfit-Bold.ttf
        - asset: assets/fonts/outfit/Outfit-ExtraBold.ttf
        - asset: assets/fonts/outfit/Outfit-ExtraLight.ttf
        - asset: assets/fonts/outfit/Outfit-Light.ttf
        - asset: assets/fonts/outfit/Outfit-Medium.ttf
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
        - asset: assets/fonts/outfit/Outfit-SemiBold.ttf
        - asset: assets/fonts/outfit/Outfit-Thin.ttf
